config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cats
  resources :owners
  get 'pages/index'

  get 'pages/about'

  root 'pages#index'

end

app/models/breed.rb
class Breed < ActiveRecord::Base
  has_many :cats

  validates :breed, presence: true
end

# == Schema Information
#
# Table name: breeds
#
#  id         :integer          not null, primary key
#  breed      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/cat.rb
class Cat < ActiveRecord::Base
  belongs_to :owner
  belongs_to :breed

  validates :name, :owner_id, :breed_id, presence: true

  has_attached_file :avatar,
    :styles => {
      :medium => "300x300#",
      :thumb => "100x100#" },
    :default_url => ":style_missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_attachment_size :avatar, :less_than => 3.megabytes, :unless => Proc.new {|m| m[:avatar_file_name].blank?}
end

# == Schema Information
#
# Table name: cats
#
#  id                  :integer          not null, primary key
#  name                :string
#  owner_id            :integer
#  breed_id            :integer
#  dob                 :date
#  allergies           :string
#  vet_name            :string
#  vet_phone           :string
#  in_daycare          :boolean
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#
# Indexes
#
#  index_cats_on_breed_id  (breed_id)
#  index_cats_on_owner_id  (owner_id)
#

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :cats

  validates :last_name, :first_name, :phone, presence: true

  def lastfirst
    "#{last_name}, #{first_name}"
  end
end

# == Schema Information
#
# Table name: owners
#
#  id              :integer          not null, primary key
#  last_name       :string
#  first_name      :string
#  phone           :string
#  emergency_name  :string
#  emergency_phone :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  admin                  :boolean          default(FALSE)
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Restrict access to admin module for non-admin users
  def authenticate_admin_user!
    raise SecurityError unless current_user.try(:admin?)
  end

  rescue_from SecurityError do |exception|
    redirect_to root_url, alert: 'You do not have access to that feature.'
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_admin_user!, except: [:index, :show]

  # GET /cats
  # GET /cats.json
  def index
    @breeds = Breed.all
    breed_ids = params[:breed_ids]

    if params[:search]
      @cats = Cat.where("name LIKE ?", "%#{params[:search]}%")
      if @cats.size.zero?
        flash[:notice] = "No result found"
        @cats = Cat.all
      end
    elsif params[:breed_ids]
      @cats = Cat.where(breed_id: params[:breed_ids])
      if @cats.size.zero?
        flash[:notice] = "No cats of that breed"
        @cats = Cat.all
      end
    else
      @cats = Cat.all
    end
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to cats_path, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:name, :owner_id, :breed_id, :dob, :allergies, :vet_name, :vet_phone, :in_daycare, :avatar)
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_admin_user!, except: [:index, :show]

  # GET /owners
  # GET /owners.json
  def index
    if params[:search_owner]
      @owners = Owner.where("last_name LIKE ?", "%#{params[:search_owner]}%")
      if @owners.size.zero?
        flash[:notice] = "No result found"
        @owners = Owner.all
      end
    else
      @owners = Owner.all
    end
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:last_name, :first_name, :phone, :emergency_name, :emergency_phone)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cats/_form.html.erb
<%= form_for(@cat) do |f| %>
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% @cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "Mittens" %>
  </div>
  <div class="field form-group">
    <%= f.label :owner_id %><br>
    <%= f.collection_select :owner_id, Owner.all.order(:last_name), :id, :lastfirst, {prompt: "Select an owner"}, {class: "form-control"} %>
  </div>
  <div class="field form-group">
    <%= f.label :breed_id %><br>
    <%= f.collection_select :breed_id, Breed.all.order(:breed), :id, :breed, {prompt: "Select a breed"}, {class: "form-control"} %>
  </div>
  <div class="field form-group">
    <%# TODO: Change to a datepicker once we learn that later %>
    <%= f.label "Date of Birth" %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="field form-group">
    <%= f.label :allergies %><br>
    <%= f.text_field :allergies, class: "form-control", placeholder: "catnip, wheat" %>
  </div>
  <div class="field form-group">
    <%= f.label :vet_name %><br>
    <%= f.text_field :vet_name, class: "form-control", placeholder: "Dr. Doolittle" %>
  </div>
  <div class="field form-group">
    <%= f.label :vet_phone %><br>
    <%= f.text_field :vet_phone, class: "form-control", placeholder: "504-555-1212" %>
  </div>
  <div class="field form-group">
    <%= f.label :in_daycare %><br>
    <%= f.check_box :in_daycare %>
  </div>
  <div class="field form-group">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing Cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<h1>Our Kitties</h1>

<p>Filter by:</p>
<p>
  <% @breeds.each do |breed| %>
    <a href="?breed_ids=<%= breed.id %>"><button class="btn btn-default btn-xs"><%= breed.breed %></button></a>
  <% end %>
</p>

<div class="row">
  <% @cats.each do |cat| %>
    <div class="col-sm-4">
      <div class="panel panel-default <%= 'panel-success' if cat.in_daycare %>">
        <div class="panel-heading">
          <h3 class="panel-title"><%= cat.name %> <%= cat.try(:owner).try(:last_name) %></h3>
        </div>
        <div class="panel-body">
          <%= form_for(cat, url: cat_path(cat), :html => {class: "form-inline"}) do |f| %>
            <% if cat.in_daycare %>
              <%= f.hidden_field :in_daycare, :value => false %>
              <%= f.submit "Check Out", class: "btn btn-warning btn-xs" %>
            <% else %>
              <%= f.hidden_field :in_daycare, :value => true %>
              <%= f.submit "Check In", class: "btn btn-success btn-xs" %>
            <% end %>
          <% end %>

          <%= image_tag cat.avatar.url(:medium), class: "img-responsive" %>
          <%= link_to fa_icon("eye", text: 'Show'), cat, class: "btn btn-primary btn-xs" %>
          <%= link_to fa_icon("pencil", text: 'Edit'), edit_cat_path(cat), class: "btn btn-warning btn-xs" %>
          <%= link_to fa_icon("trash-o", text: 'Delete'), cat, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'New Cat', new_cat_path, class: "btn btn-success" %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form' %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<div class="row">
  <h1>Cat Details</h1>
</div>
<div class="row">
  <div class="col-sm-4">
    <%= image_tag @cat.avatar.url(:medium), class: "img-responsive" %>
  </div>
  <div class="col-sm-8">
    <h3><%= @cat.name + " " + @cat.owner.last_name %></h3>

    <p>
      <strong>Owner:</strong>
      <%= link_to "#{@cat.owner.first_name} #{@cat.owner.last_name}", @cat.owner %>
    </p>

    <p>
      <strong>Breed:</strong>
      <%= @cat.breed.breed %>
    </p>

    <p>
      <strong>Dob:</strong>
      <%= @cat.dob.stamp("March 1, 1999") %>
    </p>

    <p>
      <strong>Allergies:</strong>
      <%= @cat.allergies %>
    </p>

    <p>
      <strong>Vet name:</strong>
      <%= @cat.vet_name %>
    </p>

    <p>
      <strong>Vet phone:</strong>
      <%= @cat.vet_phone %>
    </p>

    <p>
      <strong>In daycare:</strong>
      <%= @cat.in_daycare %>
    </p>
  </div>
</div>



<%= link_to fa_icon("pencil", text: 'Edit'), edit_cat_path(@cat), class: "btn btn-primary" %>
<%= link_to 'Back', cats_path, class: "btn btn-default" %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('cat_icon_small.png', class: "img-responsive"), root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Owners", owners_url %></li>
        <li><%= link_to "Cats", cats_url %></li>
        <li><%= link_to "About", pages_about_url %></li>
      </ul>

      <%= form_tag("/cats", method: "get", role: "search", class: "navbar-form navbar-left") do %>
        <div class="form-group">
          <%= text_field_tag(:search, nil, placeholder: "Mittens", class: "form-control input-sm") %>
        </div>
        <%= submit_tag("Search", class: "btn btn-primary btn-sm") %>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="welcome">Welcome <%= current_user.email %></li>
          <li><%= link_to fa_icon('cog', text: "Account"), edit_user_registration_path %></li>
          <li><%= link_to fa_icon('sign-out', text: 'Logout'), destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to fa_icon('check-circle-o', text: 'Sign Up'), new_user_registration_path %></li>
          <li><%= link_to fa_icon('sign-in', text: "Login"), new_user_session_path %></li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>KittyDaycare</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/cosmo/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <%= render 'layouts/navbar' %>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% elsif alert.present?
       %>
       <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class: "form-control", placeholder: "Jane" %>
  </div>
  <div class="field form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class: "form-control", placeholder: "Smith" %>
  </div>
  <div class="field form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control", placeholder: "504-555-1212" %>
  </div>
  <div class="field form-group">
    <%= f.label :emergency_name %><br>
    <%= f.text_field :emergency_name, class: "form-control", placeholder: "Eleanor Smith" %>
  </div>
  <div class="field form-group">
    <%= f.label :emergency_phone %><br>
    <%= f.text_field :emergency_phone, class: "form-control", placeholder: "713-555-1212" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>Owners</h1>

<%= form_tag("/owners", method: "get", role: "search", class: "form-inline") do %>
  <div class="form-group">
    <%= text_field_tag(:search_owner, nil, placeholder: "Smith", class: "form-control") %>
  </div>
  <%= submit_tag("Search", class: "btn btn-primary") %>
<% end %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th>Phone</th>
      <th>Emergency name</th>
      <th>Emergency phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.order(:last_name).each do |owner| %>
      <tr>
        <td><%= owner.last_name %></td>
        <td><%= owner.first_name %></td>
        <td><%= owner.phone %></td>
        <td><%= owner.emergency_name %></td>
        <td><%= owner.emergency_phone %></td>
        <td><%= link_to fa_icon("eye", text: 'Show'), owner, class: "btn btn-primary btn-xs" %></td>
        <td><%= link_to fa_icon("pencil", text: 'Edit'), edit_owner_path(owner), class: "btn btn-warning btn-xs" %></td>
        <td><%= link_to fa_icon("trash-o", text: 'Delete'), owner, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path, class: "btn btn-success" %>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<h1>Owner Details</h1>
<h3><%= @owner.first_name %> <%= @owner.last_name %></h3>
<p>
  <strong>Phone:</strong>
  <%= @owner.phone %>
</p>

<p>
  <strong>Emergency name:</strong>
  <%= @owner.emergency_name %>
</p>

<p>
  <strong>Emergency phone:</strong>
  <%= @owner.emergency_phone %>
</p>

<h3><%= @owner.first_name %>'s Cats</h3>

<div class="row">
  <% @owner.cats.each do |cat| %>
    <div class="col-sm-4">
      <div class="panel panel-default <%= 'panel-success' if cat.in_daycare %>">
        <div class="panel-heading">
          <h3 class="panel-title"><%= cat.name %> <%= cat.try(:owner).try(:last_name) %></h3>
        </div>
        <div class="panel-body">
          <%= image_tag cat.avatar.url(:medium), class: "img-responsive" %>
          <%= link_to fa_icon("eye", text: 'Show'), cat, class: "btn btn-primary btn-xs" %>
          <%= link_to fa_icon("pencil", text: 'Edit'), edit_cat_path(cat), class: "btn btn-warning btn-xs" %>
          <%= link_to fa_icon("trash-o", text: 'Delete'), cat, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to fa_icon("pencil", text: 'Edit'), edit_owner_path(@owner), class: "btn btn-primary" %>
<%= link_to 'Back', owners_path, class: "btn btn-default" %>

app/views/pages/about.html.erb
<h1>About Herding Cats</h1>
<p>Our fake business is located in the heart of the Mid-City neighborhood New Orleans.  Come check us out!</p>
<h1>Our Team</h1>
<p>This application was built by Sia Karamalegos as a learning Rails application for the Tech Talent South summer 2015 cohort.</p>
<h3>Social Media</h3>
<p>Follow Sia on GitHub and Twitter:</p>
<p><a href="https://github.com/siakaramalegos" target="_blank"><%= fa_icon "github", class: "fa-2x" %></a>   <a href="https://twitter.com/thegreengreek" target="_blank"><%= fa_icon "twitter", class: "fa-2x" %></a></p>
<h3>Tech Talent South</h3>
<p>Want to learn more about Tech Talent South?  Click <a href="http://techtalentsouth.com/" target="_blank">here</a>!</p>

app/views/pages/index.html.erb
</div>
<div class="jumbotron">
  <h1>Herding Cats</h1>
  <p>The best and maybe only kitty daycare around town...</p>
  <br>
  <p><%= link_to "See our cats", cats_path, class: "btn btn-primary" %></p>
</div>
<div class="container-fluid" id="features">
  <div class="row text-center">
    <div class="col-md-4">
      <%= fa_icon "heart", class: "fa-5x" %>
      <h3>Love</h3>
      <p>We care for your cats as if they were our own.  From check-in to check-out, trust that your cat is in the best care.</p>
    </div>
    <div class="col-md-4">
      <%= fa_icon "money", class: "fa-5x" %>
      <h3>Class</h3>
      <p>We know what it takes to keep your cats happy during their "spa day" here at Herding Cats.</p>
    </div>
    <div class="col-md-4">
      <%= fa_icon "glass", class: "fa-5x" %>
      <h3>Style</h3>
      <p>Because your feline deserves it.</p>
    </div>
  </div>